#!/usr/bin/env bash

weekday=$(date '+%A')

leisure=(
	'fiddling with my [dotfiles](https://github.com/bewuethr/dotfiles)'
	'finally adding refraction to my [terminal raytracer](https://github.com/bewuethr/bash-raytracer)'
	'polishing my [static site generator](https://github.com/bewuethr/pandoc-bash-blog)'
	'crafting a fascinating [blog post](https://www.benjaminwuethrich.dev)'
)

case $weekday in
	Saturday | Sunday)
		activity=${leisure[RANDOM % ${#leisure[@]}]}
		;;
	*)
		activity='working for [this bunch](https://github.com/kohofinancial)'
		;;
esac

cat <<- EOF > README.md
	### Hi there :wave:

	It's $weekday! During my waking hours, I might be $activity.
EOF
