#!/usr/bin/env bash

leisure=(
	'fiddling with my [dotfiles](https://github.com/bewuethr/dotfiles)'
	'finally adding refraction to my [terminal raytracer](https://github.com/bewuethr/bash-raytracer)'
	'polishing my [static site generator](https://github.com/bewuethr/pandoc-bash-blog)'
	'crafting a fascinating [blog post](https://www.benjaminwuethrich.dev)'
)

work=(
	'clicking some merge buttons'
	'moving some Jira tickets'
	'reviewing some pull requests'
	'interviewing a potential new colleague'
	'making a service more micro'
)
work=("${work[@]/#/'working for [this bunch](https://github.com/kohofinancial), '}")

read -r weekday hour <<< "$(date '+%A +-H')"

case $hour in
	[0-7])
		activity="I'm probably sleeping."
		;;
	*)
		case $weekday in
			Saturday | Sunday)
				activity="I might be ${leisure[RANDOM % ${#leisure[@]}]}."
				;;
			*)
				activity="I'm probably ${work[RANDOM % ${#work[@]}]}."
				;;
		esac
		;;
esac

cat <<- EOF > README.md
	### Hi there :wave:

	It's $weekday! $activity
EOF

# Suppress detached HEAD warning
git config advice.detachedHead false

# Set git name and email
git config --global user.name "github-actions"
git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

if [[ -n $(git status --porcelain) ]]; then
	git add README.md
	git commit --message "Update README"
	git push
fi
