#!/usr/bin/env bash

leisure=(
	'fiddling with my [dotfiles](https://github.com/bewuethr/dotfiles)'
	'finally adding refraction to my [terminal raytracer](https://github.com/bewuethr/bash-raytracer)'
	'polishing my [static site generator](https://github.com/bewuethr/pandoc-bash-blog)'
	'crafting a fascinating [blog post](https://www.benjaminwuethrich.dev)'
	'watching [YouTube videos about relay computers](https://youtube.com/playlist?list=PL_1HsIiuOfg3QA91DUd9kGJjQoOHwlt5Q)'
	'reading a [book](https://www.goodreads.com/review/list/37130358-benjamin?ref=nav_mybooks&shelf=currently-reading)'
	'tweaking my [Slack workspace analyzer action](https://github.com/bewuethr/slack-analyzer)'
	'fighting with Jekyll to make [this](https://swissclubto.github.io) better'
)

work=(
	'clicking some merge buttons'
	'moving some Jira tickets'
	'reviewing some pull requests'
	'interviewing a potential new colleague'
	'making a service more micro'
	'overthrowing the banking establishment'
	'maintaining a Git mailmap'
	'figuring out who should take care of which service'
	'de-flaking a test'
	'polishing a command line interface'
	'making a reusable workflow more reusable'
)
work=("${work[@]/#/'working for [this bunch](https://github.com/kohofinancial), '}")

getweather() {
	local -n w=$1
	local location=$2
	# shellcheck disable=SC2034
	readarray -t w < <(curl "wttr.in/$location?m&lang=en&format=%C\n%t\n")
}

updatestatus() {
	local emoji=$1
	local message=$2
	gh api graphql \
		--raw-field query='
			mutation UpdateStatus{
			  changeUserStatus(input:{emoji:"'"$emoji"'",message:"'"$message"'"}) {
			    clientMutationId
			    status {
			      emoji
			      message
			      updatedAt
			      user {
			        login
			      }
			    }
			  }
			}
		' | jq .
}

update() {
	local location=$1
	local weekday hour
	read -r weekday hour <<< "$(date '+%A %-H')"

	local activity emoji message
	case $hour in
		[0-7])
			activity="I'm probably sleeping."
			emoji=':sleeping:'
			message='Snoozing'
			;;
		1[89] | 2[0-3])
			activity="I might be ${leisure[RANDOM % ${#leisure[@]}]}."
			emoji=':man_juggling:'
			message='Juggling'
			;;
		*)
			case $weekday in
				Saturday | Sunday)
					activity="I might be ${leisure[RANDOM % ${#leisure[@]}]}."
					emoji=':joystick:'
					message='Playing'
					;;
				*)
					activity="I'm probably ${work[RANDOM % ${#work[@]}]}."
					emoji=':nerd_face:'
					message='Work work work'
					;;
			esac
			;;
	esac

	local weather
	getweather weather "$location"

	if [[ ${weather[*]} == 'Unknown location'* ]]; then
		echo "Updating README with $weekday and $activity, weather unknown..."
		cat <<- EOF > README.md
			### Hi there :wave:

			It's $weekday! $activity

			Weather in $location: who knows, wttr.in is currently down...
		EOF
	else
		echo "Updating README with $weekday and $activity, weather ${weather[*]}..."
		cat <<- EOF > README.md
			### Hi there :wave:

			It's $weekday! $activity

			Weather in $location: ${weather[0],}, at ${weather[1]}.
		EOF
	fi

	echo "Updating profile status with $emoji and $message..."
	updatestatus "$emoji" "$message"
}

push() {
	# Set git name and email
	git config --global user.name 'github-actions'
	git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

	if [[ -n $(git status --porcelain) ]]; then
		echo "Change detected; pushing new README..."
		git add README.md .github/location/locationdata.yml
		git commit --message 'Update README and maybe location'
		git push
	fi
}

main() {
	local location=$1
	update "$location"
	push
}

[[ ${BASH_SOURCE[0]} == "$0" ]] && main "$1"
